export enum ActionType {
  FETCH_REPO_SUCCESS = "FETCH_REPO_SUCCESS",
  FETCH_REPOS_REQUEST = "FETCH_REPOS_REQUEST",
  FETCH_REPOS_ERROR = "FETCH_REPOS_ERROR",

  SET_INPUT = "SET_INPUT",

  GET_README_SUCCESS = "GET_README_SUCCESS",
  GET_README_ERROR = "GET_README_ERROR",
  GET_README_REQUEST = "GET_README_REQUEST",

  GET_USER_REPO_REQUEST = "GET_USER_REPO_REQUEST",
  GET_USER_REPO_SUCCESS  ="GET_USER_REPO_SUCCESS",
  GET_USER_REPO_ERROR = "GET_USER_REPO_ERROR",

  INVERT_MODAL = "INVERT_MODAL"
}
